apiVersion: v1
kind: Namespace
metadata:
  {{- if .Values.isPr }}
  annotations:
    "janitor/expires": {{ dateInZone "2006-01-02T15:04" (now | date_modify "+2.0h" ) "UTC" | quote  }}
  {{- end }}
  name: {{ if .Values.isPr }} {{ template "prnamespacename" . }}{{ else }}{{ template "namespacename" . }}{{ end }}