name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Generate manifests to apply
        if: github.ref != 'refs/heads/master'
        run: |
          cd $GITHUB_WORKSPACE/argocd-app
          helm template test -f values.yaml . --output-dir ./generated --set isPR=true,repoUrl=${{ github.event.repository.html_url }},currentBranch=$GITHUB_REF
          
          cat ./generated/argocd-app/templates/*.yaml



      # Runs a set of commands using the runners shell
      #- name: Apply
      #  if: github.ref != 'refs/heads/master'
      #  uses: actions-hub/kubectl@master
      #  env:
      #    KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      #  with:
      #    args: apply -f $GITHUB_WORKSPACE/generated/argocd-app/templates/
